### ISSUE TITLE
Unmet peer dependency (coffeelint@^1) prevents grunt from running

### ISSUE THREAD

**Issue by annyanich** [stromhalm/apo#2]
I tried installing APO by following the instructions in the README.  

```
$ npm install -g grunt-cli
$ git clone https://github.com/stromhalm/apo.git
$ cd apo
$ npm install
```

It seems that coffeelint is not getting installed, and that makes grunt fail to run:

```
$ npm install

[...]

APT-Online@0.1.1 /.../apo
├── coffee-script@1.10.0 
├── UNMET PEER DEPENDENCY coffeelint@^1
├─┬ connect-modrewrite@0.9.0 

[...]

npm WARN grunt-coffeelint@0.0.13 requires a peer of coffeelint@^1 but none was installed.
$ grunt
Loading "coffeelint.js" tasks...ERROR
>> Error: Cannot find module 'coffeelint'
Warning: Task "coffeelint" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2017-06-29 16:42:19 UTC+2)
loading tasks  5ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 5ms

```

**Comment by stromhalm** [comment]
Hey @annyanich, thanks for your feedback!
I just added CoffeeLint as a npm dependency. Now it should start successfully.
Just run `git pull` to get the latest changes and `npm install` again (both inside the project directory) and Grunt should be able to compile again.

Adrian

**Comment by annyanich** [comment]
Thanks @stromhalm!  That fixed it.

Ann
